### PR TITLE
Add option to middleware to getVisitorId from req and res

### PR DESCRIPTION
**Pull request by esclapes**
I realized that `visitorId` was not being populated in `trackVisits` for `buffer-login` because it expects it to be in `req.session.visitorId`

The config option `getVisitorId` will allow us to get the value from `res.locals.visitorId` instead.

### CODE REVIEW

**Comment by esclapes** [comment]
Hey @djfarrelly @michael-erasmus, I see that travis complaining about the `package-lock.json` being out of sync:

`Invalid: lock file's @bufferapp/buda@0.5.2-beta1 does not satisfy @bufferapp/buda@0.6.1`

I don't think that's related to my change here. Would you mind having a look?

**Comment by michael-erasmus** [comment]
> Hey @djfarrelly @michael-erasmus, I see that travis is complaining about the package-lock.json being out of sync:

> Invalid: lock file's @bufferapp/buda@0.5.2-beta1 does not satisfy @bufferapp/buda@0.6.1

Hey @esclapes! Thanks for the heads up. I think this should now be resolved with this commit: https://github.com/bufferapp/buffer-js-buffermetrics/commit/0406bdc10e224060d0dacd69d45acb9647f93568

**Comment by esclapes** [comment]
Hey @michael-erasmus Would you be up for publishing a minor version with this change? 

I am not sure what's the schedule/process to get new versions out, so let me know if I am missing some context here.

**Comment by philippemiguet** [comment]
Hey @esclapes you should feel free to publish a new version on npm and update other repos which will require that new version :) I did it few months ago [here](https://github.com/bufferapp/buffer-js-buffermetrics/commit/4386749e7660487ff55f5644910bd9e274a961c8) if it helps.

**Comment by esclapes** [comment]
O great @philippemiguet I will do that.

Michael, sorry for the ping :sweat_smile:

**Pull request merged**
