### PR TITLE
0.6.x

### PR DESCRIPTION
**Pull request by mallen5311**
Heya @michael-erasmus ,

This PR follows up with our conversations from earlier in the week, and adds the following fields to the signup and visit events:

- visit useragent device and os
- signup ip and referrer

I didn't see another branch that you might have going for the other changes you are working on, but maybe we can merge this branch with that one when you are ready?

### CODE REVIEW

**Comment by michael-erasmus** [comment]
Hey @mallen5311! Thanks for the PR!

We might want to merge this PR with mine over here: https://github.com/bufferapp/buffer-js-buffermetrics/pull/35/files if that feels ok with you?

**Comment by mallen5311** [comment]
Hi @michael-erasmus !  Sure thing, that feels great to me 👍 😄 .

**Comment by michael-erasmus** [comment]
@mallen5311, ok happy to jump in with that (I was planning on working on this today)

**Comment by mallen5311** [comment]
Closing this, as it is now redundant :)

**Pull request closed without merging**
